services:
  gomora-dapp:
    build: .
    container_name: ${API_NAME}
    mem_limit: "3g"
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
    networks:
      - proxy
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./storage/images:/app/build/storage/images
      - ./storage/metadata:/app/build/storage/metadata
      - ./storage/nft-mint-upload.log:/app/build/storage/nft-mint-upload.log
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${API_NAME}.entrypoints=http"
      - "traefik.http.routers.${API_NAME}.rule=Host(`${API_URL_REST}`)"
      - "traefik.http.routers.${API_NAME}-secure.entrypoints=https"
      - "traefik.http.routers.${API_NAME}-secure.rule=Host(`${API_URL_REST}`)"
      - "traefik.http.routers.${API_NAME}-secure.tls=true"
      - "traefik.http.routers.${API_NAME}-secure.tls.certresolver=http"
      - "traefik.http.routers.${API_NAME}-secure.service=${API_NAME}"
      - "traefik.http.services.${API_NAME}.loadbalancer.server.port=${API_URL_REST_PORT}"
      - "traefik.docker.network=proxy"

networks:
  proxy:
    external: true
